apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "dscp-api.fullname" . }}-config
  labels:
    {{- include "dscp-api.labels" . | nindent 4 }}
data:
  port: {{ .Values.config.port | quote }}
  {{- if .Values.config.externalOrigin }}
  externalOrigin: {{ .Values.config.externalOrigin }}
  {{- end }}
  {{- if .Values.config.externalPathPrefix }}
  externalPathPrefix: {{ .Values.config.externalPathPrefix }}
  {{- end }}
  logLevel: {{ .Values.config.logLevel }}
  nodeHost: {{ include "dscp-api.node-host" . }}
  {{- if .Values.config.externalIpfsHost }}
  ipfsHost: {{ .Values.config.externalIpfsHost }}
  {{- else if .Values.dscpIpfs.enabled }}
  ipfsHost: {{ template "dscp-ipfs.fullname" .Subcharts.dscpIpfs }}-api
  {{- end }}
  {{- if .Values.config.externalIpfsPort }}
  ipfsPort: {{ .Values.config.externalIpfsPort | quote }}
  {{- else if .Values.dscpIpfs.enabled }}
  ipfsPort: {{ template "dscp-ipfs.ipfsApiPort" .Subcharts.dscpIpfs }}
  {{- end }}
  {{- if eq .Values.config.auth.type "JWT" }}
  authJwksUri: {{ .Values.config.auth.jwksUri }}
  authAudience: {{ .Values.config.auth.audience }}
  authIssuer: {{ .Values.config.auth.issuer }}
  {{- end }}
  substrateStatusPollPeriodMs: {{ .Values.config.substrateStatusPollPeriodMs | quote }}
  substrateStatusTimeoutMs: {{ .Values.config.substrateStatusTimeoutMs | quote }}
  ipfsStatusPollPeriodMs: {{ .Values.config.ipfsStatusPollPeriodMs | quote }}
  ipfsStatusTimeoutMs: {{ .Values.config.ipfsStatusTimeoutMs | quote }}
  authType: {{ .Values.config.auth.type }}
