apiVersion: v2
name: dscp-api
appVersion: '4.6.5'
description: A Helm chart for dscp-api
version: '4.6.5'
type: application
dependencies:
  - name: dscp-node
    version: '4.2.1'
    repository: https://digicatapult.github.io/dscp-node/
    condition: dscpNode.enabled
    alias: dscpNode

  - name: dscp-ipfs
    version: '2.6.1'
    repository: https://digicatapult.github.io/dscp-ipfs/
    condition: dscpIpfs.enabled
    alias: dscpIpfs
maintainers:
  - name: digicatapult
    email: opensource@digicatapult.org.uk
    url: www.digicatapult.org.uk
